### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by labidiaymen** [sustainland/sustain#2]
### Feature on the roadmap

- [ ] Deno support
- [ ] Schema-based service and module generator (Schematic)
- [ ] Dashboard to edit/add schema
- [ ] Graphql connector
- [ ] OpenApi support Enhancement
- [ ] VS code extensions

This list can be updated during the lifecycle of the project
